### PR TITLE
Add Climate- & HumiditySensor, Change TemperatureSensor

### LINKED ISSUE #426: TemperatureSensor does not work because it is missing required temperature range attributes
According to https://developers.home.google.com/cloud-to-cloud/traits/temperaturecontrol, the min and max thresholds are required for the **TemperatureControl** trait: 

<html>
<body>

Attributes | Type | Description
-- | -- | --
temperatureRange | Object | Required.<br>Supported temperature range of the device.
minThresholdCelsius | Number | Required.<br>Minimum temperature for the range, in degrees Celsius.
maxThresholdCelsius | Number | Required.<br>Maximum temperature for the range, in degrees Celsius.

</body>
</html>

### LINKED ISSUE #427: [Feature Request] add HumiditySensor
The device type **Sensor** supports the trait **HumiditySetting**. This could be used for displaying humidity.

### PR DESCRIPTION
**Pull request by michikrug**
While working on #426, we noticed that using `TemperatureControl` does not show any UI for the sensor in the Google Home app.
Apparently, using the `TemperatureSetting` trait does the trick.
Therefore, I adjusted the `TemperatureSensor` to use the other trait.
In addition to that, I added a `HumiditySensor` (only for humidity) and a `ClimateSensor` (for both humidity and temperature).

This supersedes #428 as working with ranges did not fix the issue.

Screenshot_20230103-212322
Screenshot_20230103-212333
Screenshot_20230103-212339

---

Resolves #426
Resolves #427

---

ToDo

- [x] Prepare PR for openhab-webui to add the new annotations

### CODE REVIEW

**Comment by robnielsen** [comment]
@michikrug, do you have a Nest Hub? I noticed that the current version displays both the setpoint and current temperature for `TemperatureSensor`. Hopefully, it will still work with your changes.

**Comment by robnielsen** [comment]
PXL_20230105_183126758 - Copy

**Comment by michikrug** [comment]
> @michikrug, do you have a Nest Hub? I noticed that the current version displays both the setpoint and current temperature for `TemperatureSensor`. Hopefully, it will still work with your changes.

No. I don't.

Well, I have removed the setpoint one as I thought this makes no sense. At least in Google Home the single one is displayed.

**Comment by michikrug** [comment]
openHAB Web UI was updated here: https://github.com/openhab/openhab-webui/pull/1648

**Pull request merged**
