### PR TITLE
[SpecialColorLight] Add Color capabilities

### LINKED ISSUE #234: Support Color for SpecialColorLight
Please support a color item in the grouped light (SpecialColorLight), so it's possible to build a light that supports different shades of white (warm to cold) and actual color (RGB/HSV).

Something like this would be great:
```
Group  lightGroup { ga="Light" [ useKelvin=true, colorTemperatureRange="2000,9000" ] }
Switch powerItem           (lightGroup) { ga="lightPower" }
Dimmer brightnessItem      (lightGroup) { ga="lightBrightness" }
Number colortempratureItem (lightGroup) { ga="lightColorTemperature" }
Color  colorItem           (lightGroup) { ga="lightColor" }
```

### PR DESCRIPTION
**Pull request by cromefire**
Fixes #234

This _should_ enable a `SpecialColorLight` to also have a color channel (`lightColor`).

Don't really have any idea have any idea on how to test it though without having to setup a whole bunch of stuff with Google and exposing my openhab server.

### CODE REVIEW

**Comment by cromefire** [comment]
The only thing missing now is to reset the color if a color temperature is set, but I'm not sure how to do that. As `ColorAbsoluteTemperature.convertParamsToValue` only sets one item, but it'd need so set both `lightColorTemperature` and `lightColor`.

**Comment by cromefire** [comment]
Okay I went over the code again and it should actually be okay, although I don't really have a way to test it, without setting up a google cloud subscription, a public facing openhab, etc.

**Comment by michikrug** [comment]
> Okay I went over the code again and it should actually be okay, although I don't really have a way to test it, without setting up a google cloud subscription, a public facing openhab, etc.

Thanks for the update. I will set up something at my end to test this.

**Comment by michikrug** [comment]
Code at least looks fine. Will have a test run in my setup and then I think it is ready to merge. :)

**Comment by michikrug** [comment]
Should work now as expected

**Pull request merged**
