### PR TITLE
Added action.devices.commands.ThermostatSetMode 

### PR DESCRIPTION
**Pull request by alibahba**
Should fix 37.
Added action.devices.commands.ThermostatSetMode to change the thermostat mode via GA

### CODE REVIEW

**Comment by alibahba** [comment]
Some fixes for executing multiple commands in 1 request.

**Comment by alibahba** [comment]
Added support for scenes due to the scene tag. Scenes will be visible in google assistant as scene and no longer as a switch.

**Comment by alibahba** [comment]
Added the outlet!
Use the [ "Outlet" ] tag and your item will appear as a true outlet in the Google Home app.

**Comment by marziman** [comment]
Hi @alibahba ,

First of all: Thanks and great you contribute! 
I wanted to merge these things in.
There are some things which are not so ideal:
- You should def. use a verified signature and sign your commits
- It is not so good, that you made a PR for ThermostatSetMode but introduced new cool features :-)

So maybe we can divide this PR off? So I can test it much easier and we can lower the risk of 
creating unwanted side effects? Would be great...

Let me know what you think?

**Comment by alibahba** [comment]
Hi @marziman,

For now, I think I can't sign the current commits.
I will fix that for feature commits.

Sorry I have added new features in the same PR.
For now, in my opinion, that's not a big problem.

The features Scene and Outlet are really small. 
All the rest is for the thermostat issue's.
In the above commits you can see what code is changed for whitch issue.
Off course ive test it all on my own google actions test environment.

**Pull request closed without merging**
