### PR TITLE
Add advanced Fan capabilities

### PR DESCRIPTION
**Pull request by michikrug**
This PR adds a lot of new functionality to FAN devices (AirPurifier, Fan, Hood).

This includes:
- OnOff (separate power switch if used as a group)
- FanSpeed (separate fan speed if used as a group)
- Modes (yes, for the first time modes are available)
- SensorState (for FilterLifeTime and PM2.5 - no clue how to query those)

Info:
- This is based on #222 and needs a rebase after merge

TODO:
- Add documentation

### CODE REVIEW

**Comment by marziman** [comment]
Hi @michikrug if you want we can make a session soon and discuss this and the other PR?
Will speed it up. WDYT?

**Comment by michikrug** [comment]
This is still somewhat work in progress. I have additional changes in the pipeline that I will likely integrate first.

**Comment by SeveranExp** [comment]
@michikrug hey friend! Sorry to bug you, I’m pinging you because I’m currently in the middle of planning an air purification setup, and was thinking of using this function from the google docs - in particular the sensor state for the sensors. (Even created a feature request before checking here.. oops).
Would it be possible to have this function available in openHAB?? I understand it’s a work in progress, of course :)

**Comment by michikrug** [comment]
Superseded by #405

**Pull request closed without merging**
