### PR TITLE
query pays respect to traits

### PR DESCRIPTION
**Pull request by mdopp**
Possible solution for #23 

QUERY returns now a value for each trait, or at least for "onoff" and "brightness". 
For "onoff", it might be necessary to return for category "DimmableLight" an "ON" if the value is '!== "0"' instead of '== "ON"'. But I am not sure if this should be based on category or on type.

Also the intent is now only handled in index.js, not in openhab.js anymore to simplify the code a little.

This change has not been tested! Its more a suggestion how it could work a little better. That's why the two commits are not sqashed.

### CODE REVIEW

**Comment by sk8ter** [comment]
Nice! I wanted to fix same thing, but you were first :)

**Comment by sk8ter** [comment]
Deployed locally, but with query like "What is the brightness level of my light?" it still returns web search results. Do you experience the same behaviour?

**Comment by mdopp** [comment]
@skater: does it answer which lights are on? Or still return that it does not know the status

**Comment by sk8ter** [comment]
@mdopp Yes, it answers! For me it always returned status, but wrong one.

I have all lights switched of, but still says they are on.
Here is some log:
<pre>
result for tradfri_0220_19449f32_65537_brightness: {"link":"...65537_brightness","state":"0","type":"Dimmer","name":"tradfri_65537_brightness","label":"Brightness","category":"DimmableLight","tags":["Lighting"],"groupNames":[]}
</pre>
<pre>
Got all results: [{"id":"tradfri_65538_brightness","data":{"online":true,"brightness":0,"on":true}},{"id":"tradfri_65537_brightness","data":{"online":true,"brightness":0,"on":true}}]
</pre>
It compares: "0" === 0

**Comment by sk8ter** [comment]
@skimdankish I came to the same conclusion. Just wanted to make sure that it is not my env/setup, since official Google info says it should work.

**Pull request closed without merging**
