### PR TITLE
Use Metadata instead of Tags

### PR DESCRIPTION
**Pull request by michikrug**
With this PR (based on ["Complete Rework"](https://github.com/openhab/openhab-google-assistant/pull/118)), I changed the way how to expose items to Google Assistant from tags to metadata.
~This will require all users to migrate their configuration.~
Former supported tags will continue to work - but no additional functionality will be supported.

Metadata can be added either using the item files as seen below or via console using the smarthome commands: `smarthome:metadata add ThermostatLR ga THERMOSTAT`

With tags (current usage):
`Switch TVSwitch "TV Switch" <screen> ["Switchable"]`

With Metadata (values are not case sensitive):
`Switch TVSwitch "TV Switch" <screen> { ga="SWITCH" }`

This will allow more advanced configurations like:
`Switch HouseAlarm "House Alarm" { ga="SECURITYSYSTEM" [ tfaPin="3521" ] }`
`Switch Something "Some Switch with Acknowledge" { ga="SWITCH" [ tfaAck=true ] }`

`Group ThermostatLR "Thermostat Living Room" { ga="THERMOSTAT" [ useFahrenheit=true ] }`

More to come...

**New features:**
- Two-factor Authentication (Acknowledge `[ tfaAck=true ]` & PIN `[ tfaPin="3521" ]`)
- `Speaker` Type with `Volume` trait (`Dimmer`)
- `Fan` Type with OnOff & `FanSpeed` trait (`Dimmer`)
- `Hood` Type with OnOff & `FanSpeed` trait (`Dimmer`)
- `Camera` Type with `CameraStream` trait (`String`)
- `inverted=true` option for `Rollershutter` items
- `useFahrenheit=true` option for `Thermostat` items
- `roomHint` and `structureHint` as config options
- Support for `synonyms` metadata namespace
- Proper setup of temperature sensor only Thermostats
- Option to configure available modes for Thermostats `[modes="on,off,heat"]`
- Option to use separate high and low setpoint items
- Support for color temperature commands (automatic conversion)

### CODE REVIEW

**Comment by michikrug** [comment]
@marziman
As I read it on your post in the forum, you would like to maintain both tags and metadata. I would not go for this as it would mean enormous effort to provide both solutions with downsides too.
I really would like to "force" all users to switch to only using metadata and do a clean transition to a new version.

**Comment by gytisgreitai** [comment]
> . I would not go for this as it would mean enormous effort to provide both solutions with downsides too.

@michikrug don't want to nag, but since you've fixed the tags version, you could probably run it in parallel at least for a while and have branching in code? E.g.  upon sync if you find at least one google metadata config, use metadata, else revert to tag. When doing metada, store on customData flag which indicates if execute should be handled by tag or metadata handler. Afaik this way it would not be extremely difficult to keep tags solution for backwards compatability.

**Comment by Fiftiz** [comment]
Hi @michikrug , you think it's possible to create like Alexa a group for the device TV ? 

for exemple for Alexa : 

```
Group gTV "TV" {alexa="Endpoint.Speaker"}
Number TV_channel "channel [%s]" (gTV) {alexa="ChannelController.channel", channel="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
Dimmer TV_Volume "Volume [%s]" (gTV) {alexa="SpeakerVolume", channel="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
............ and also item with Mediastate trait
```

So with in group the action.devices.types.TV , and inside traits : action.devices.traits.MediaState  (play , pause ...) and action.devices.traits.Channel (change channel) and action.devices.traits.Volume (change volume)

I ask the question again because I did not have the answer :) thank you

**Comment by michikrug** [comment]
> > . I would not go for this as it would mean enormous effort to provide both solutions with downsides too.
> 
> @michikrug don't want to nag, but since you've fixed the tags version, you could probably run it in parallel at least for a while and have branching in code? E.g. upon sync if you find at least one google metadata config, use metadata, else revert to tag. When doing metada, store on customData flag which indicates if execute should be handled by tag or metadata handler. Afaik this way it would not be extremely difficult to keep tags solution for backwards compatability.

With the latest commits I added backward compatibility with tags.
So it should (with limited configuration options) still work with the "old-fashioned" tags.

**Comment by michikrug** [comment]
> Hi @michikrug , you think it's possible to create like Alexa a group for the device TV ?
> 
> for exemple for Alexa :
> 
> ```
> Group gTV "TV" {alexa="Endpoint.Speaker"}
> Number TV_channel "channel [%s]" (gTV) {alexa="ChannelController.channel", channel="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
> Dimmer TV_Volume "Volume [%s]" (gTV) {alexa="SpeakerVolume", channel="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
> ............ and also item with Mediastate trait
> ```
> 
> So with in group the action.devices.types.TV , and inside traits : action.devices.traits.MediaState (play , pause ...) and action.devices.traits.Channel (change channel) and action.devices.traits.Volume (change volume)
> 
> I ask the question again because I did not have the answer :) thank you

I already started implementing this. Unfortunately, this is not well documented (officially not at all).

**Comment by marziman** [comment]
@michikrug
As I am in foreign country and somehow busy, I couldnt well test the compatbikity stuff. I woukd love to release it together with the other changes.

Did you had a chance to test it properly?

**Comment by michikrug** [comment]
@marziman I will spend the holidays to add more tests to ensure proper functionality

But so far, I am running a mixed setup without any issues for some weeks now :)

**Comment by stefanuytterhoeven** [comment]
any chance you can add this metadata in the paper ui ? 
At this moment, I managed to keep my items file empty, and define everything through the paper ui....

**Comment by michikrug** [comment]
> any chance you can add this metadata in the paper ui ?
> At this moment, I managed to keep my items file empty, and define everything through the paper ui....

Not from my knowledge. But it's quite easy using the console or the REST API..

**Comment by marziman** [comment]
Hi @michikrug
many thanks for the good work. I took a quick look and seems to be fine. I guess only our tests for this is a bit weak. I still would merge this. Do you want to add more tests? We can also make a secon PR with Tests. I feel like this PR gets too big otherwise..

BR Mehmet

**Pull request merged**
