### PR TITLE
Fix conversion of Fahrenheit to Celsius (#126)

### LINKED ISSUE #126: "Fahrenheit" breake the thermostat in GH app
It seems like after GA integration v.2 has been merged, using "Fahrenheit" in the Thermostat tag, will break the thermostat values wihtin the Google Home app.

See more info in here:
https://community.openhab.org/t/openhab-google-assistant-integration-v2-0/85573/84

### PR DESCRIPTION
**Pull request by michikrug**
With this PR the conversion of Fahrenheit to Celsius is fixed (resolves #126).
There was the conversion from string to number missing.

To ensure proper functionality a first set of tests is added.

During writing more tests, I also discovered a bug with the brightness state that is fixed now.

### CODE REVIEW

**Comment by michikrug** [comment]
@marziman can we merge this?

**Comment by hotrodwinston** [comment]
When will these changes go live? My system still won't sync with Google assistant.

**Comment by wtf911** [comment]
I'd like to know as well. I posted on ticket #126 as well just hoping to get some visibility to know when we'll see this in effect.

"If I'm using openhab 2.5.0 stable with myopenhab will I need to update my openhab to get this fix? Or will the "myopenhab website/platform" need to be updated on openhabs end? Aka if this something I do on my end or they do on their end since I use the free myopenhab site."

**Comment by hotrodwinston** [comment]
Reporting that after unlinking and relinking my openhab account and setting my thermostat mode to hear instead of auto it is now working. Wish auto mode worked but I'll take switching.

**Pull request merged**
