### PR TITLE
Make sceneReversible configurable for scene device

### PR DESCRIPTION
**Pull request by janwo**
I added the possibility to adjust sceneReversible meta for scenes, see https://developers.google.com/assistant/smarthome/traits/scene

As sceneReversible is currently set to true, I made it the default setting. Therefore users need to set sceneReversible explicitly to false.

### CODE REVIEW

**Comment by janwo** [comment]
@michikrug  Test seems to be fine but task fails due to some permission issues.

**Comment by michikrug** [comment]
> @michikrug  Test seems to be fine but task fails due to some permission issues.

I know. Will be fixed within the deployment PR latest or even earlier with a separate fix.

**Review by michikrug — APPROVED** [review]

**Comment by michikrug** [comment]
@janwo Looks fine.

Next time I would advise you not to use your main branch for PRs :)

**Comment by janwo** [comment]
> @janwo Looks fine.
> 
> Next time I would advise you not to use your main branch for PRs :)

Why? :D

**Pull request merged**
