### PR TITLE
Enhanced SecuritySystem support

### PR DESCRIPTION
**Pull request by duanemck**
Expands the SecuritySystem functionality to enable everything supported by the GA trait:
* Adds ArmLevels
* Adds StatusReport trait
* Adds StatusReport when arming fails (showing blocking zones)

Some refactoring of the default command was done to enable the above but the new functionality is possibly reusable for other commands:
* Functionality to check the state of an item before making a change. This allows the ArmDisarm command to fail when attempting to arm a system that is already armed.
* Functionality to enforce that the state of the item is requested (with a configurable settling delay) after setting the state. This allows the SecuritySystem to report an arm/disarm failure.
* Functionality to allow a command to bypass the configured PIN in certain situations. This allows the user to specify that the PIN is only needed when disarming the alarm.  

Tests and docs also updated for the above.

Implements #186 and #146

### CODE REVIEW

**Comment by michikrug** [comment]
Thank you very much for your contribution. I will take some time to review this.

Since I will be on vacation for the next two weeks, I kindly ask for your patience :)

**Comment by duanemck** [comment]
No problem, thank you.

**Comment by michikrug** [comment]
Not to give you the feeling of ignorance. I just have not had time yet :(

**Comment by michikrug** [comment]
@duanemck Hi. Thanks again for all the effort.

I went through all the code and added some changes here and there.
I also tested most of the stuff.

Do you also have a test setup available?
I struggle a bit in validating especially the error cases e.g. arm/disarm failure and state reports. Could you tests this (again)?
Or can you tell me on how to test this with Google Assistant and what the expected answers should be?

**Comment by duanemck** [comment]
> @duanemck Hi. Thanks again for all the effort.
> 
> I went through all the code and added some changes here and there. I also tested most of the stuff.
> 
> Do you also have a test setup available? I struggle a bit in validating especially the error cases e.g. arm/disarm failure and state reports. Could you tests this (again)? Or can you tell me on how to test this with Google Assistant and what the expected answers should be?

Hi @michikrug, thanks so much for going through it. Happy to retest from my side. I'm just away on holiday at the moment so will only be able to test when I'm back next weekend.

**Comment by duanemck** [comment]
Hi @michikrug sorry, things got busy when I got back and I forgot. This evening I managed to pull the latest changes and I have tested it locally on my alarm and it's all working as expected.

**Comment by duanemck** [comment]
And I like the idea of the SimpleSecuritySystem, my change would overcomplicate things for people who simply want an ON/OFF :)

**Review by michikrug — APPROVED** [review]

**Pull request merged**
