### PR TITLE
Bugfix: Sends the correct shutters commands to OpenHab

### PR DESCRIPTION
**Pull request by pythen**
The process intent "action.devices.DISCONNECT" implemented

### CODE REVIEW

**Comment by pythen** [comment]
Sends the correct shutters commands to OpenHab

Google send value --> OpenHab receives command
0 --> DOWN
100 --> UP
[1 .. 99] --> [99 .. 1]

OpenHab sends status --> Google receives value
[0 .. 100] --> [100 .. 0]

**Comment by macfly92** [comment]
Works as expected for me, thanks you.

**Comment by enrico-cc** [comment]
I saw that the bugfix has been merged, but I am still experiencing the inverted commands issue.
Should I do something to update my local setup or some kind of publishing is still needed?
Thanks,
Enrico

**Comment by mvalla** [comment]
Needs to be punished on google cloud  by @marziman . 

But actually since no one  is able to control Thermostats anymore is probably better to wait this to be corrected too before publishing ...

**Pull request merged**
