### PR TITLE
Fix thermostat group documentation

### PR DESCRIPTION
**Pull request by eikowagenknecht**
Clarify usage of modes config option, fix wrong description of thermostatTemperatureSetpointHigh/Low items.

Related to #139.

### CODE REVIEW

**Comment by eikowagenknecht** [comment]
Apparently editing using the GitHub web interface prevents correctly creating PRs because of Signoff address mismatch. Will correct this when at home.

**Comment by eikowagenknecht** [comment]
Finally had time to correct the signoff. Should be mergeable now.

**Comment by michikrug** [comment]
@eikowagenknecht could you please rebase on latest master and fix possible conflicts?

**Comment by eikowagenknecht** [comment]
@michikrug Since you fixed the modes part yourself now, I removed it from the PR. Only Humidity -> Temperature remains. This should be mergeable again now.

**Pull request merged**
