### PR TITLE
Fix obvious issues

### PR DESCRIPTION
**Pull request by michikrug**
After opening this project in my IDE it automatically highlighted some issues that I fixed with that PR.

Most of them are formatting things, but there was also a critical thing:
the wrong access of `thermostatModeDenormalize`.

### CODE REVIEW

**Comment by marziman** [comment]
Many thanks for your PR!
I think mainly formatting right? If ok I will merge another one first before bringing this in?

BR Mehmet

**Comment by marziman** [comment]
Can you maybe re-touch it shortly? I would like to keep your contribution, instead of repeating it by myself. This conflict happened as I pickeup another PR before yours. Sorry.

**Comment by michikrug** [comment]
Sure, I will rebase

**Comment by michikrug** [comment]
I would close this in favor of the complete rework that includes all this.

**Pull request closed without merging**
